project_id              = "devops-gcp-470517"
region1                 = "europe-central2"
region2                 = "europe-west1"
vpc_name                = "demo-vpc"
subnet1_cidr            = "10.10.0.0/24"
subnet2_cidr            = "10.20.0.0/24"
artifact_repo_name      = "hello-repo"
artifact_repo_location  = "europe-central2"
image_name              = "europe-central2-docker.pkg.dev/devops-gcp-470517/hello-repo/hello-python:3.0"
cloud_run_service_name  = "hello-python-svc"
labels = {
  project = "static-website"
  owner   = "devops"
  env     = "dev"
}